// <auto-generated />
using System;
using InsuranceManagementSystemMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceManagementSystemMVC.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    [Migration("20230521075924_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adminId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__AD0500A6C7ABCA31");

                    b.ToTable("admin", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.CityMaster", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("City_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("State_Id");

                    b.HasKey("CityId")
                        .HasName("PK__city_mas__DE9CEC38771DD4B4");

                    b.HasIndex("StateId");

                    b.ToTable("city_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.CountryMaster", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Country_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("CountryId")
                        .HasName("PK__country___8037C7D643E9E2B0");

                    b.ToTable("country_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("First_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Last_name");

                    b.HasKey("CustomerId")
                        .HasName("PK__customer__8CB382B19F2D5FD5");

                    b.ToTable("customers", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.GenderMaster", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("Gender_id");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("GenderId")
                        .HasName("PK__gender_m__AF740A3C4D92378F");

                    b.ToTable("gender_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.InsuranceTypeMaster", b =>
                {
                    b.Property<int>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_id");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Insurance_type");

                    b.HasKey("InsuranceId")
                        .HasName("PK__insuranc__FFF1644B9C333A9C");

                    b.ToTable("insurance_type_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.MaritalStatusMaster", b =>
                {
                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Marital_status_id");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Marital_status");

                    b.HasKey("MaritalStatusId")
                        .HasName("PK__marital___EB830C2D851EA3C0");

                    b.ToTable("marital_status_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.ModeOfPremiumMaster", b =>
                {
                    b.Property<int>("ModeOfPremiumId")
                        .HasColumnType("int")
                        .HasColumnName("mode_of_premium_id");

                    b.Property<string>("ModeOfPremium")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mode_of_premium");

                    b.HasKey("ModeOfPremiumId")
                        .HasName("PK__mode_of___61535EFC29C4C980");

                    b.ToTable("mode_of_premium_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.NomineeDetail", b =>
                {
                    b.Property<long>("NomineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Nominee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NomineeId"));

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Aadhar_number");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date");

                    b.Property<int?>("GenderId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Gender_id");

                    b.Property<long>("MobileNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("Mobile_number");

                    b.Property<string>("NomineeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nominee_name");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PAN_number");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("Policy_id");

                    b.Property<int?>("RelationshipId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Relationship_id");

                    b.HasKey("NomineeId")
                        .HasName("PK__nominee___917234FC2B1A1421");

                    b.HasIndex("GenderId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RelationshipId");

                    b.HasIndex(new[] { "AadharNumber" }, "UQ__nominee___097AF695B810004D")
                        .IsUnique();

                    b.HasIndex(new[] { "PanNumber" }, "UQ__nominee___0CB01CC46680DD9B")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNumber" }, "UQ__nominee___9E090FFF6CB3CDBF")
                        .IsUnique();

                    b.ToTable("nominee_details", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("Payment_Date");

                    b.Property<int?>("PaymentTypeId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Payment_type_id");

                    b.Property<long>("PremiumId")
                        .HasColumnType("bigint")
                        .HasColumnName("Premium_Id");

                    b.HasKey("PaymentId")
                        .HasName("PK__payments__DA638B199F3EDA5F");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("PremiumId");

                    b.ToTable("payments", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PaymentTypeMaster", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Payment_type_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Payment_type");

                    b.HasKey("PaymentTypeId")
                        .HasName("PK__payment___19563F1C73524910");

                    b.ToTable("payment_type_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PersonalDetail", b =>
                {
                    b.Property<long>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Personal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonalId"));

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Aadhar_number");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("City_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("Country_id");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("GenderId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Gender_id");

                    b.Property<int?>("MaritalStatusId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Marital_status_id");

                    b.Property<long>("MobileNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("Mobile_number");

                    b.Property<string>("PanNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PAN_number");

                    b.Property<long>("PostalCode")
                        .HasColumnType("bigint")
                        .HasColumnName("Postal_code");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("State_id");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("PersonalId")
                        .HasName("PK__personal__732C802264EA0558");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("StateId");

                    b.HasIndex(new[] { "AadharNumber" }, "UQ__personal__097AF695983FC34F")
                        .IsUnique();

                    b.HasIndex(new[] { "PanNumber" }, "UQ__personal__0CB01CC4E84EC167")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNumber" }, "UQ__personal__9E090FFF73DA8EAF")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__personal__A9D1053460EF173E")
                        .IsUnique();

                    b.ToTable("personal_details", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyDetail", b =>
                {
                    b.Property<long>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PolicyId"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("Customer_id");

                    b.Property<DateTime?>("DateOfExpire")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_expire");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_issue");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status_id");

                    b.HasKey("PolicyId")
                        .HasName("PK__policy_d__4569BF19CA8DD8D5");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("StatusId");

                    b.ToTable("policy_details", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyValue", b =>
                {
                    b.Property<long>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Premium_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PremiumId"));

                    b.Property<int>("AmountOfPeriod")
                        .HasColumnType("int")
                        .HasColumnName("Amount_of_period");

                    b.Property<decimal?>("InsuredDeclaredValue")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Insured_Declared_value");

                    b.Property<int?>("ModeOfPremiumId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("mode_of_premium_id");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("policy_id");

                    b.Property<decimal?>("PremiumToBePaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("premium_to_be_paid");

                    b.HasKey("PremiumId")
                        .HasName("PK__policy_v__368DE5EA17999DD8");

                    b.HasIndex("ModeOfPremiumId");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__policy_v__47DA3F02C1715153")
                        .IsUnique();

                    b.ToTable("policy_value", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.RelationshipMaster", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Relationship_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RelationshipId")
                        .HasName("PK__relation__1D4D88B87EC455F9");

                    b.ToTable("relationship_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.StateMaster", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("State_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("Country_Id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("StateId")
                        .HasName("PK__state_ma__AF9444CFB582AA42");

                    b.HasIndex("CountryId");

                    b.ToTable("state_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.StatusMaster", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("StatusId")
                        .HasName("PK__status_m__5191052418AFB1B4");

                    b.ToTable("status_master", "insurance");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.CityMaster", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.StateMaster", "State")
                        .WithMany("CityMasters")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("fk_stateF_id");

                    b.Navigation("State");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.NomineeDetail", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.GenderMaster", "Gender")
                        .WithMany("NomineeDetails")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gender_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.PolicyDetail", "Policy")
                        .WithMany("NomineeDetails")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("fk_policy2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.RelationshipMaster", "Relationship")
                        .WithMany("NomineeDetails")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationship_id");

                    b.Navigation("Gender");

                    b.Navigation("Policy");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.Payment", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.PaymentTypeMaster", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_type_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.PolicyValue", "Premium")
                        .WithMany("Payments")
                        .HasForeignKey("PremiumId")
                        .IsRequired()
                        .HasConstraintName("fk_primium_id");

                    b.Navigation("PaymentType");

                    b.Navigation("Premium");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PersonalDetail", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.CityMaster", "City")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("fk_city2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.CountryMaster", "Country")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_country2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.Customer", "Customer")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_customer2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.GenderMaster", "Gender")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gender2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.MaritalStatusMaster", "MaritalStatus")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_marital_status2_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.StateMaster", "State")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("fk_state2_id");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("Gender");

                    b.Navigation("MaritalStatus");

                    b.Navigation("State");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyDetail", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.Customer", "Customer")
                        .WithMany("PolicyDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.InsuranceTypeMaster", "Insurance")
                        .WithMany("PolicyDetails")
                        .HasForeignKey("InsuranceId")
                        .IsRequired()
                        .HasConstraintName("fk_insurance_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.StatusMaster", "Status")
                        .WithMany("PolicyDetails")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("fk_status_id");

                    b.Navigation("Customer");

                    b.Navigation("Insurance");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyValue", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.ModeOfPremiumMaster", "ModeOfPremium")
                        .WithMany("PolicyValues")
                        .HasForeignKey("ModeOfPremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mode_of_premium_id");

                    b.HasOne("InsuranceManagementSystemMVC.Models.PolicyDetail", "Policy")
                        .WithOne("PolicyValue")
                        .HasForeignKey("InsuranceManagementSystemMVC.Models.PolicyValue", "PolicyId")
                        .IsRequired()
                        .HasConstraintName("fk_policy3_id");

                    b.Navigation("ModeOfPremium");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.StateMaster", b =>
                {
                    b.HasOne("InsuranceManagementSystemMVC.Models.CountryMaster", "Country")
                        .WithMany("StateMasters")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_countryF_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.CityMaster", b =>
                {
                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.CountryMaster", b =>
                {
                    b.Navigation("PersonalDetails");

                    b.Navigation("StateMasters");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.Customer", b =>
                {
                    b.Navigation("PersonalDetails");

                    b.Navigation("PolicyDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.GenderMaster", b =>
                {
                    b.Navigation("NomineeDetails");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.InsuranceTypeMaster", b =>
                {
                    b.Navigation("PolicyDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.MaritalStatusMaster", b =>
                {
                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.ModeOfPremiumMaster", b =>
                {
                    b.Navigation("PolicyValues");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PaymentTypeMaster", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyDetail", b =>
                {
                    b.Navigation("NomineeDetails");

                    b.Navigation("PolicyValue")
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.PolicyValue", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.RelationshipMaster", b =>
                {
                    b.Navigation("NomineeDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.StateMaster", b =>
                {
                    b.Navigation("CityMasters");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("InsuranceManagementSystemMVC.Models.StatusMaster", b =>
                {
                    b.Navigation("PolicyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
